### ISSUE TITLE
Separate database for pdns and poweradmin schemas

### ISSUE THREAD

**Issue by peterthomassen** [poweradmin/poweradmin#296]
For better separation between pdns' own tables and the ones added by poweradmin, I would like to suggest the option to specify two different database connections.

This way, poweradmin tables which may be used in development environments only don't have to stick around in production servers.

**Comment by bynicolas** [comment]
I believe this would provide better management and the ability to use concurrent GUI in a clean way.

**Comment by edmondas** [comment]
I've added a new `$pdns_db_name` setting to the config file which would allow you to use PowerDNS tables from a different schema, but it hasn't been fully tested and is not yet supported by the installer.

**Comment by edmondas** [comment]
You can now specify a database name for PowerDNS tables using the `pdns_db_name` parameter. This is currently supported only by MySQL since PostgreSQL doesn't support cross-database queries and SQLite doesn't support this feature.

Having multiple database connections would be too complicated from an implementation perspective, requiring changes in different places. It's also unclear how aggregations across different databases would be handled properly.

Example configuration:
```php
'database' => [
    'host' => 'pgsql',
    'name' => 'poweradmin',
    'user' => 'pwa',
    'password' => 'PASSWORD',
    'type' => 'pgsql',
    'pdns_db_name' => 'pdns',
],
```

This is now supported by the installer with selection of custom database (MySQL only).

**Comment by flames** [comment]
how to setup this with Docker / Compose?
DB_PDNS_DB_NAME=pdns
or
PA_PDNS_DB_NAME=pdns
thanks in advance

**Comment by edmondas** [comment]
@flames I updated the entry point script to support PA_PDNS_DB_NAME and pushed the changes to master.

**Comment by flames** [comment]
hi, thanks! Tested 4.0.1 just now.

Actually, i tried the custom config only, because this didn't worked for the separate pdns db (https://github.com/poweradmin/poweradmin/issues/753#issuecomment-3149774718)

here my compose.yaml:

```
services:
  poweradmin:
    image: edmondas/poweradmin:4.0.1
    ports:
      - 8084:80
    environment:
      - DB_TYPE=mysql
      - DB_HOST=192.168.111.17
      - DB_USER=pdns
      - DB_PASS='my'
      - DB_NAME=poweradmin
      - DNS_NS1=ns1.mydomain.ch
      - DNS_NS2=ns2.mydomain.ch
      - DNS_HOSTMASTER=hostmaster.mydomain.ch
      - PA_API_ENABLED=true
      - PA_API_DOCS_ENABLED=true
      - PA_PDNS_API_URL=http://192.168.111.17:7081
      - PA_PDNS_API_KEY=mypdnsapykey
      - PA_PDNS_DB_NAME=pdns
networks: {}
```

Log:
```
poweradmin-poweradmin-1  | [2025-08-05 20:45:52] Poweradmin Docker Container Starting...
poweradmin-poweradmin-1  | [2025-08-05 20:45:52] Processing Docker secrets...
poweradmin-poweradmin-1  | [2025-08-05 20:45:52] No custom config found. Generating settings.php from environment variables...
poweradmin-poweradmin-1  | [2025-08-05 20:56:18] Poweradmin Docker Container Starting...
poweradmin-poweradmin-1  | [2025-08-05 20:56:18] Processing Docker secrets...
poweradmin-poweradmin-1  | [2025-08-05 20:56:18] No custom config found. Generating settings.php from environment variables...
```

After that container just stops.

in the config readme it should be DB_PDNS_DB_NAME=pdns
modern config https://docs.poweradmin.org/configuration/database/

```
return [
    'database' => [
        'host' => 'localhost',
        'port' => '3306',
        'name' => 'powerdns',
        'user' => 'poweradmin',
        'password' => 'your_secure_password',
        'type' => 'mysql',
        'charset' => 'latin1',
        'file' => '',
        'debug' => false,
        'pdns_db_name' => 'powerdns', // Optional: Use when PowerDNS tables are in a separate database <---- this one
    ],
];
```

excuse me, i don't know, how to use docker compose with the master branch. seen, you have updated the dockerhub image to 4.0.1, tried that.
